# Generated by Django 3.0.8 on 2020-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('url', models.TextField()),
                ('color_name', models.TextField()),
                ('color_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('image_url', models.TextField()),
                ('colors', models.ManyToManyField(to='main.Color')),
            ],
        ),
    ]
